### ISSUE TITLE
IntegrityErrors when running

### ISSUE THREAD

**Issue by Boerner1337** [mbertaboni/telecylance#1]
Hey Maurizio, first of all: awesome job! Really appreciate your work on that! 
I would really love to see how the bot evolves! In that matter I just tested a bit around. 

Script is running, Bot is working as expected. However my commandprompt gives me some errors:

2018-12-04 22:20:24,434 - JobQueue - ERROR - An uncaught error was raised while executing job get_threats
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/telegram/ext/jobqueue.py", line 245, in tick
    job.run(self.bot)
  File "/Library/Python/2.7/site-packages/telegram/ext/jobqueue.py", line 372, in run
    self.callback(bot, self)
  File "telecylance.py", line 320, in get_threats
    "INSERT INTO temp_data (threat_id,timestamp,tenant_id) VALUES (?,?,?)", (unique_threat, unique_date, tid_val))
IntegrityError: UNIQUE constraint failed: temp_data.threat_id
2018-12-04 22:20:56,403 - JobQueue - ERROR - An uncaught error was raised while executing job get_threats
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/telegram/ext/jobqueue.py", line 245, in tick
    job.run(self.bot)
  File "/Library/Python/2.7/site-packages/telegram/ext/jobqueue.py", line 372, in run
    self.callback(bot, self)
  File "telecylance.py", line 320, in get_threats
    "INSERT INTO temp_data (threat_id,timestamp,tenant_id) VALUES (?,?,?)", (unique_threat, unique_date, tid_val))
IntegrityError: UNIQUE constraint failed: temp_data.threat_id
2018-12-04 22:21:23,479 - JobQueue - ERROR - An uncaught error was raised while executing job get_threats
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/telegram/ext/jobqueue.py", line 245, in tick
    job.run(self.bot)
  File "/Library/Python/2.7/site-packages/telegram/ext/jobqueue.py", line 372, in run
    self.callback(bot, self)
  File "telecylance.py", line 320, in get_threats
    "INSERT INTO temp_data (threat_id,timestamp,tenant_id) VALUES (?,?,?)", (unique_threat, unique_date, tid_val))
IntegrityError: UNIQUE constraint failed: temp_data.threat_id
2018-12-04 22:21:53,499 - JobQueue - ERROR - An uncaught error was raised while executing job get_threats
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/telegram/ext/jobqueue.py", line 245, in tick
    job.run(self.bot)
  File "/Library/Python/2.7/site-packages/telegram/ext/jobqueue.py", line 372, in run
    self.callback(bot, self)
  File "telecylance.py", line 320, in get_threats
    "INSERT INTO temp_data (threat_id,timestamp,tenant_id) VALUES (?,?,?)", (unique_threat, unique_date, tid_val))
IntegrityError: UNIQUE constraint failed: temp_data.threat_id

Can you investigate into that? What is causing that problems? 

Best, 
Kevin

**Comment by mbertaboni** [comment]
Hello Kev,
I've made some changes to the code mainly related to the uniqueness of the threat whenever is found the same threat. 
Code updated
